### PR TITLE
Add tests for PatientFormController and sonar/jacoco to pom.xml

### PR DESCRIPTION
**Pull request by ldf92**
Add tests for PatientFormController.

Add sonar/jacoco plugins to pom.xml so that we can get coverage information.

### CODE REVIEW

**Comment by wluyima** [comment]
What is the ticket number?

**Comment by dkayiwa** [comment]
@ldf92 what ticket number is this?
I would also use a separate pull request for the sonar changes instead of mixing them with those of the unit tests.

**Comment by teleivo** [comment]
just a little remark. you are using the old test style. the AT verifies annotation is now only in the javadoc of the test, see https://wiki.openmrs.org/display/docs/Generate+Test+Case+Plugin

**Comment by dkayiwa** [comment]
@ldf92 create new pull requests that separate the two.

**Pull request closed without merging**
