### PR TITLE
Fix for: Forgotten Password Form Leaks Valid Usernames [TRUNK-3933]

### PR DESCRIPTION
**Pull request by bholagabbar**
Fixed the valid usernames being leaked. If the username is invalid, a fake random questions is assigned to him on the basis of the hash-value of the persons name and returns false everytime

### CODE REVIEW

**Comment by dkayiwa** [comment]
@bholagabbar can you separate formatting changes from others?

**Comment by bholagabbar** [comment]
I did not understand. How do I do that?

**Comment by dkayiwa** [comment]
Make a copy of your changes. Then revert to ensure that there are no changes to commit. Add in the changes from the backup, one by one, and commit.

**Comment by bholagabbar** [comment]
That is to preserve the formatting?

**Comment by dkayiwa** [comment]
Yes!

**Pull request closed without merging**
