### PR TITLE
RA-1897:Fix Typo error in legacyui on admin page

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/LUI-176
cc @k-joseph  @dkayiwa  Kindly review thanks

### CODE REVIEW

**Comment by dkayiwa** [comment]
Should this be RA or LegacyUI JIRA project?

**Comment by sherrif10** [comment]
Ohh sorry it should be in Legacyui jira Project, let me correct it thanks

**Comment by sherrif10** [comment]
is it fine to leave it there, the only difference remains on branches

**Comment by sherrif10** [comment]
Opened a clear renamed branch [here](https://github.com/openmrs/openmrs-module-legacyui/pull/134), thought while renaming a branch in it also re changes the commit also but it doesnt , so am closing this

**Pull request closed without merging**
