### PR TITLE
Add travis.yml for PR integration

### PR DESCRIPTION
**Pull request by teleivo**
Add .travis.yml to ensure new PRs do not break the build.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @teleivo 👍

**Comment by teleivo** [comment]
@dkayiwa your welcome! I think someone with permission would need to activate it on travis under the openmrs account see https://travis-ci.org/openmrs/openmrs-module-legacyui its not yet active

**Comment by dkayiwa** [comment]
That looks like @rkorytkowski :)

**Comment by rkorytkowski** [comment]
Done: https://travis-ci.org/openmrs/openmrs-module-legacyui/builds/142839592

**Pull request merged**
