### PR TITLE
LUI-84-dispalying a useful information when the user is locked out

### PR DESCRIPTION
**Pull request by mozzy11**
i added a class to return a value to he login page when user is locked out

https://issues.openmrs.org/browse/LUI-83

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash these commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by mozzy11** [comment]
thx done , the above two pull requests are the same, no need to squash them..i justmade amistake when pushing them , but its actually the same, i just pushed two commits at ago

**Comment by mozzy11** [comment]
as in i pushed the same commit twice

**Comment by mozzy11** [comment]
i finally managed to squash the commits

**Comment by dkayiwa** [comment]
Did you take a look at the above travis failure?

**Comment by mozzy11** [comment]
oooh well, i ha forgoten about this ticket but let me ..tryto clean it

**Comment by mozzy11** [comment]
by the time i did this , was very new to open mrs, ddnt know the coding convetions, let me re do it just

**Comment by dkayiwa** [comment]
@mozzy11 did you give up on this?

**Comment by mozzy11** [comment]
noo, its wat am going to start on next week. let me get done with this
emrapi migration ticket

**Comment by dkayiwa** [comment]
You are the author and hence have full control of the pull request. 😊

**Comment by mozzy11** [comment]
alryt. thx then

**Pull request closed without merging**
