### PR TITLE
Added WebUtil.escapeHTML function to ProviderListItem

### PR DESCRIPTION
**Pull request by Parth59**
Had raised https://github.com/openmrs/openmrs-module-legacyui/pull/141 for the following. After which @isears requested to modify the server-side code instead of the JS files. So I tried solving EMPT64 with changes in the following server File:- omod/src/main/java/org/openmrs/web/dwr/ProviderListItem.java. Had to revert the changes of the following PR https://github.com/openmrs/openmrs-module-legacyui/pull/152 to make it error free. 

Steps to reproduce can be found here.
https://docs.google.com/document/d/1GJNMRlGTRV45St6WSjnD_FjW84aoNxY9HzGbpwoBrro/edit?usp=sharing

Link to ticket:
https://issues.openmrs.org/browse/RA-1865

### CODE REVIEW

**Review by isears — CHANGES_REQUESTED** [review]
Ok, I remember this now. 

In general, I definitely prefer this server-side approach to patching. The reason #152 got merged in, however, is because it patched EMPT-46 as well as EMPT-64, even if the JS-based patch was less desirable.

@Parth59 if you can include a server-side patch for EMPT-46 in this PR, I'll merge it in.

**Comment by HerbertYiga** [comment]
> can include a server-side patch for EMPT-46 in this PR

beautiful

**Comment by Parth59** [comment]
Hi Team,
Thanks for the review @isears 
I worked with @maxhark  for the same and have raised the following PR's with their respected serverside fixes.

i) EMPT60 :- https://github.com/openmrs/openmrs-module-legacyui/pull/158
ii) EMPT46 :-https://github.com/openmrs/openmrs-module-legacyui/pull/159

**Comment by isears** [comment]
Ok thanks @Parth59 and @maxhark for working together to figure this out. I've merged #158 and #159 so I'm going to go ahead and close this one

**Comment by Parth59** [comment]
Hi @isears  .

This PR's fixes EMPT64. Whereas  the below PR's fixes EMPT60 and  EMPT46. Kindly review it to fix EMPT64.
i) EMPT60 :- https://github.com/openmrs/openmrs-module-legacyui/pull/158
ii) EMPT46 :-https://github.com/openmrs/openmrs-module-legacyui/pull/159

**Review by isears — APPROVED** [review]
Sorry must have misinterpreted, thanks for the reminder @Parth59 !

**Pull request merged**
