### PR TITLE
LUI-147 Added Global Property to re-order tabs in Patient Dashboard

### PR DESCRIPTION
**Pull request by MSUCodeFreely**
https://issues.openmrs.org/browse/LUI-147

### CODE REVIEW

**Comment by ODORA0** [comment]
@MSUCodeFreely have you taken a look at this https://wiki.openmrs.org/display/docs/Pull+Request+Tips?

**Comment by MSUCodeFreely** [comment]
@ODORA0 Yes, I made sure tests passed, made sure it was formatted using eclipse plugin, I rebased onto master, squashed the commits and updated the ticket. 

Was there something I missed?

**Comment by ODORA0** [comment]
Didn't you miss the ticket link before?

**Comment by MSUCodeFreely** [comment]
> Didn't you miss the ticket link before?

Yes, sorry. 
As soon as I replied I noticed the original description was empty.

**Comment by dkayiwa** [comment]
Can you include the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by MSUCodeFreely** [comment]
@dkayiwa  Yes, I've updated the name.

**Comment by dkayiwa** [comment]
@MSUCodeFreely can you attach some screenshots with the effects of your changes, as the JIRA ticket, as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by MSUCodeFreely** [comment]
@dkayiwa screenshots have been added to the ticket

**Comment by dkayiwa** [comment]
Closing this because we are not adding any new features to the legacyui. Only bug fixes.
Despite this, i would have merged the pull request if it did not have merge conflicts and needed no more work.

@MSUCodeFreely  thanks for the great work and am happy to reopen this if you have time to finish the remaining work.

**Pull request closed without merging**
