### PR TITLE
LUI-176:Fix Typo error in legacyui on admin page

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/LUI-176
cc @k-joseph  @dkayiwa  Kindly review thanks

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you have the commit message reference LUI-176?

**Comment by sherrif10** [comment]
Sure thanks

**Comment by sherrif10** [comment]
shall we merge this @dkayiwa

**Comment by dkayiwa** [comment]
Did you see my comment?

**Comment by sherrif10** [comment]
Yes i have updated the commit message reference on LUI-176

**Comment by dkayiwa** [comment]
That is not what i see displayed in this pr.

**Comment by sherrif10** [comment]
Thanks i have now made it clear

**Comment by dkayiwa** [comment]
Are you sure that you are looking at the commit message that this pull request displays?

**Comment by sherrif10** [comment]
Ohh   have updated the commit message thanks

**Pull request merged**
