### PR TITLE
LUI-14

### PR DESCRIPTION
**Pull request by jdegraft**
Migrated Legacy Maintenance Admin

### CODE REVIEW

**Comment by jdegraft** [comment]
Yes, I have fixed the line wrapping issue. Turned off auto format on save.

**Comment by dkayiwa** [comment]
@jdegraft are you making a pull another commit to reverse the earlier formatting?

**Comment by jdegraft** [comment]
Frankly, I don't know how to go about it.
Wouldn't it be a better idea to setup formatting as part of the build process as it is done in core?

**Comment by lluismf** [comment]
Probably, but there's no agreement on which is the limit (if any). There's
a discussion here
https://talk.openmrs.org/t/openmrs-code-formatter-styles/794/9

2015-10-29 0:48 GMT+01:00 jdegraft <notifications@github.com>:

**Comment by jdegraft** [comment]
@lluismf Thanks, I have set it to 120. I will update files and create pull request.

**Pull request merged**
